[package]
name = "wasm"
version = "0.1.0"
edition = "2024"

# [lib]
# crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4.27"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.50"
web-sys = "0.3.70"              # to access the DOM (to hide the loading text)
